/*
 * Binance Alpha REST API
 *
 * OpenAPI Specification for the Binance Alpha REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::alpha::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetExchangeInfoResponseDataSymbolsInnerFiltersInner {
    #[serde(rename = "filterType", skip_serializing_if = "Option::is_none")]
    pub filter_type: Option<String>,
    #[serde(rename = "minPrice", skip_serializing_if = "Option::is_none")]
    pub min_price: Option<String>,
    #[serde(rename = "maxPrice", skip_serializing_if = "Option::is_none")]
    pub max_price: Option<String>,
    #[serde(rename = "tickSize", skip_serializing_if = "Option::is_none")]
    pub tick_size: Option<String>,
    #[serde(rename = "stepSize", skip_serializing_if = "Option::is_none")]
    pub step_size: Option<String>,
    #[serde(rename = "maxQty", skip_serializing_if = "Option::is_none")]
    pub max_qty: Option<String>,
    #[serde(rename = "minQty", skip_serializing_if = "Option::is_none")]
    pub min_qty: Option<String>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(rename = "minNotional", skip_serializing_if = "Option::is_none")]
    pub min_notional: Option<String>,
    #[serde(rename = "maxNotional", skip_serializing_if = "Option::is_none")]
    pub max_notional: Option<String>,
    #[serde(rename = "multiplierDown", skip_serializing_if = "Option::is_none")]
    pub multiplier_down: Option<String>,
    #[serde(rename = "multiplierUp", skip_serializing_if = "Option::is_none")]
    pub multiplier_up: Option<String>,
    #[serde(rename = "bidMultiplierUp", skip_serializing_if = "Option::is_none")]
    pub bid_multiplier_up: Option<String>,
    #[serde(rename = "askMultiplierUp", skip_serializing_if = "Option::is_none")]
    pub ask_multiplier_up: Option<String>,
    #[serde(rename = "bidMultiplierDown", skip_serializing_if = "Option::is_none")]
    pub bid_multiplier_down: Option<String>,
    #[serde(rename = "askMultiplierDown", skip_serializing_if = "Option::is_none")]
    pub ask_multiplier_down: Option<String>,
}

impl GetExchangeInfoResponseDataSymbolsInnerFiltersInner {
    #[must_use]
    pub fn new() -> GetExchangeInfoResponseDataSymbolsInnerFiltersInner {
        GetExchangeInfoResponseDataSymbolsInnerFiltersInner {
            filter_type: None,
            min_price: None,
            max_price: None,
            tick_size: None,
            step_size: None,
            max_qty: None,
            min_qty: None,
            limit: None,
            min_notional: None,
            max_notional: None,
            multiplier_down: None,
            multiplier_up: None,
            bid_multiplier_up: None,
            ask_multiplier_up: None,
            bid_multiplier_down: None,
            ask_multiplier_down: None,
        }
    }
}
