/*
 * Binance Derivatives Trading Options REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_options::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptionPositionInformationResponseInner {
    #[serde(rename = "entryPrice", skip_serializing_if = "Option::is_none")]
    pub entry_price: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "side", skip_serializing_if = "Option::is_none")]
    pub side: Option<String>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<String>,
    #[serde(rename = "markValue", skip_serializing_if = "Option::is_none")]
    pub mark_value: Option<String>,
    #[serde(rename = "unrealizedPNL", skip_serializing_if = "Option::is_none")]
    pub unrealized_pnl: Option<String>,
    #[serde(rename = "markPrice", skip_serializing_if = "Option::is_none")]
    pub mark_price: Option<String>,
    #[serde(rename = "strikePrice", skip_serializing_if = "Option::is_none")]
    pub strike_price: Option<String>,
    #[serde(rename = "expiryDate", skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<i64>,
    #[serde(rename = "priceScale", skip_serializing_if = "Option::is_none")]
    pub price_scale: Option<i64>,
    #[serde(rename = "quantityScale", skip_serializing_if = "Option::is_none")]
    pub quantity_scale: Option<i64>,
    #[serde(rename = "optionSide", skip_serializing_if = "Option::is_none")]
    pub option_side: Option<String>,
    #[serde(rename = "quoteAsset", skip_serializing_if = "Option::is_none")]
    pub quote_asset: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    #[serde(rename = "bidQuantity", skip_serializing_if = "Option::is_none")]
    pub bid_quantity: Option<String>,
    #[serde(rename = "askQuantity", skip_serializing_if = "Option::is_none")]
    pub ask_quantity: Option<String>,
}

impl OptionPositionInformationResponseInner {
    #[must_use]
    pub fn new() -> OptionPositionInformationResponseInner {
        OptionPositionInformationResponseInner {
            entry_price: None,
            symbol: None,
            side: None,
            quantity: None,
            mark_value: None,
            unrealized_pnl: None,
            mark_price: None,
            strike_price: None,
            expiry_date: None,
            price_scale: None,
            quantity_scale: None,
            option_side: None,
            quote_asset: None,
            time: None,
            bid_quantity: None,
            ask_quantity: None,
        }
    }
}
