/*
 * Binance Derivatives Trading Options REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_options::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCommissionResponseCommissionsInner {
    #[serde(rename = "underlying", skip_serializing_if = "Option::is_none")]
    pub underlying: Option<String>,
    #[serde(rename = "makerFee", skip_serializing_if = "Option::is_none")]
    pub maker_fee: Option<String>,
    #[serde(rename = "takerFee", skip_serializing_if = "Option::is_none")]
    pub taker_fee: Option<String>,
}

impl UserCommissionResponseCommissionsInner {
    #[must_use]
    pub fn new() -> UserCommissionResponseCommissionsInner {
        UserCommissionResponseCommissionsInner {
            underlying: None,
            maker_fee: None,
            taker_fee: None,
        }
    }
}
