/*
 * Binance Derivatives Trading Options REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_options::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCommissionResponse {
    #[serde(rename = "commissions", skip_serializing_if = "Option::is_none")]
    pub commissions: Option<Vec<models::UserCommissionResponseCommissionsInner>>,
}

impl UserCommissionResponse {
    #[must_use]
    pub fn new() -> UserCommissionResponse {
        UserCommissionResponse { commissions: None }
    }
}
