/*
 * Binance Crypto Loan REST API
 *
 * OpenAPI Specification for the Binance Crypto Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::crypto_loan::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFlexibleLoanInterestRateHistoryResponseRowsInner {
    #[serde(rename = "coin", skip_serializing_if = "Option::is_none")]
    pub coin: Option<String>,
    #[serde(
        rename = "annualizedInterestRate",
        skip_serializing_if = "Option::is_none"
    )]
    pub annualized_interest_rate: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
}

impl GetFlexibleLoanInterestRateHistoryResponseRowsInner {
    #[must_use]
    pub fn new() -> GetFlexibleLoanInterestRateHistoryResponseRowsInner {
        GetFlexibleLoanInterestRateHistoryResponseRowsInner {
            coin: None,
            annualized_interest_rate: None,
            time: None,
        }
    }
}
