/*
 * Binance VIP Loan REST API
 *
 * OpenAPI Specification for the Binance VIP Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::vip_loan::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVipLoanAccruedInterestResponseRowsInner {
    #[serde(rename = "loanCoin", skip_serializing_if = "Option::is_none")]
    pub loan_coin: Option<String>,
    #[serde(rename = "principalAmount", skip_serializing_if = "Option::is_none")]
    pub principal_amount: Option<String>,
    #[serde(rename = "interestAmount", skip_serializing_if = "Option::is_none")]
    pub interest_amount: Option<String>,
    #[serde(rename = "annualInterestRate", skip_serializing_if = "Option::is_none")]
    pub annual_interest_rate: Option<String>,
    #[serde(rename = "accrualTime", skip_serializing_if = "Option::is_none")]
    pub accrual_time: Option<i64>,
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i64>,
}

impl GetVipLoanAccruedInterestResponseRowsInner {
    #[must_use]
    pub fn new() -> GetVipLoanAccruedInterestResponseRowsInner {
        GetVipLoanAccruedInterestResponseRowsInner {
            loan_coin: None,
            principal_amount: None,
            interest_amount: None,
            annual_interest_rate: None,
            accrual_time: None,
            order_id: None,
        }
    }
}
