/*
 * Binance Spot REST API
 *
 * OpenAPI Specifications for the Binance Spot REST API
 *
 * API documents:
 * - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)
 * - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::spot::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionRulesResponseSymbolRulesInnerRulesInner {
    #[serde(rename = "ruleType", skip_serializing_if = "Option::is_none")]
    pub rule_type: Option<String>,
    #[serde(rename = "bidLimitMultUp", skip_serializing_if = "Option::is_none")]
    pub bid_limit_mult_up: Option<String>,
    #[serde(rename = "bidLimitMultDown", skip_serializing_if = "Option::is_none")]
    pub bid_limit_mult_down: Option<String>,
    #[serde(rename = "askLimitMultUp", skip_serializing_if = "Option::is_none")]
    pub ask_limit_mult_up: Option<String>,
    #[serde(rename = "askLimitMultDown", skip_serializing_if = "Option::is_none")]
    pub ask_limit_mult_down: Option<String>,
}

impl ExecutionRulesResponseSymbolRulesInnerRulesInner {
    #[must_use]
    pub fn new() -> ExecutionRulesResponseSymbolRulesInnerRulesInner {
        ExecutionRulesResponseSymbolRulesInnerRulesInner {
            rule_type: None,
            bid_limit_mult_up: None,
            bid_limit_mult_down: None,
            ask_limit_mult_up: None,
            ask_limit_mult_down: None,
        }
    }
}
