/*
 * Binance Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::margin_trading::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarginRestrictedAssetsResponse {
    #[serde(
        rename = "openLongRestrictedAsset",
        skip_serializing_if = "Option::is_none"
    )]
    pub open_long_restricted_asset: Option<Vec<String>>,
    #[serde(
        rename = "maxCollateralExceededAsset",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_collateral_exceeded_asset: Option<Vec<String>>,
}

impl GetMarginRestrictedAssetsResponse {
    #[must_use]
    pub fn new() -> GetMarginRestrictedAssetsResponse {
        GetMarginRestrictedAssetsResponse {
            open_long_restricted_asset: None,
            max_collateral_exceeded_asset: None,
        }
    }
}
