/*
 * Binance Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::margin_trading::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryPreventedMatchesResponseInner {
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "preventedMatchId", skip_serializing_if = "Option::is_none")]
    pub prevented_match_id: Option<i64>,
    #[serde(rename = "takerOrderId", skip_serializing_if = "Option::is_none")]
    pub taker_order_id: Option<i64>,
    #[serde(rename = "makerSymbol", skip_serializing_if = "Option::is_none")]
    pub maker_symbol: Option<String>,
    #[serde(rename = "makerOrderId", skip_serializing_if = "Option::is_none")]
    pub maker_order_id: Option<i64>,
    #[serde(rename = "tradeGroupId", skip_serializing_if = "Option::is_none")]
    pub trade_group_id: Option<i64>,
    #[serde(
        rename = "selfTradePreventionMode",
        skip_serializing_if = "Option::is_none"
    )]
    pub self_trade_prevention_mode: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    #[serde(
        rename = "makerPreventedQuantity",
        skip_serializing_if = "Option::is_none"
    )]
    pub maker_prevented_quantity: Option<String>,
    #[serde(rename = "transactTime", skip_serializing_if = "Option::is_none")]
    pub transact_time: Option<i64>,
}

impl QueryPreventedMatchesResponseInner {
    #[must_use]
    pub fn new() -> QueryPreventedMatchesResponseInner {
        QueryPreventedMatchesResponseInner {
            symbol: None,
            prevented_match_id: None,
            taker_order_id: None,
            maker_symbol: None,
            maker_order_id: None,
            trade_group_id: None,
            self_trade_prevention_mode: None,
            price: None,
            maker_prevented_quantity: None,
            transact_time: None,
        }
    }
}
